# Site Info
title: SJ's blog
tagline: 'for ITS'
description: 'blog for ITS'
url: http://S2eongjin.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: S2eongjin
  description: <strong>신호제어</strong> 인간의 이동을 연구합니다
  gravatar: eb00c5fdfe26e3e1edec6963d9ce1938 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/seongjin-lee-883460239
    github:    https://github.com/S2eongjin
    #facebook:  <hide>
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:sue04206@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/picture.JPG
  caption: Global ITS

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
#disqus_short_name: 'ratsgo-github-io' # leave blank if you don't want disqus

